#@data/values-schema
---
#! all scdf options
scdf:
  deploy:
    #! deploy mode, either minikube or cloud
    mode: minikube
    #! binder type, either rabbit or kafka (needed if external binder is not defined)
    #@schema/type any=True
    binder:
  database:
    #! database type, either mysql or postgres (required)
    #@schema/type any=True
    type:
  server:
    image:
      #! dataflow server image repository id
      repository: springcloud/spring-cloud-dataflow-server
      #! dataflow server image tag (required)
      #@schema/type any=True
      tag:
  ctr:
    image:
      #! ctr image repository id
      repository: springcloud/spring-cloud-dataflow-composed-task-runner
      #! ctr image tag (required)
      #@schema/type any=True
      tag:
  skipper:
    image:
      #! skipper server image repository id
      repository: springcloud/spring-cloud-skipper-server
      #! skipper server image tag (required)
      #@schema/type any=True
      tag:
  #! external binder settings, will disable binder deployment
  binder:
    kafka:
      #@schema/type any=True
      host:
      #@schema/type any=True
      port:
    rabbit:
      #@schema/type any=True
      host:
      #@schema/type any=True
      port:
