#@data/values-schema
---
#! all scdf options
scdf:
  deploy:
    #! deploy mode, either minikube or cloud
    mode: minikube
    #! binder type, either rabbit or kafka (needed if external binder is not defined)
    binder: ""
  database:
    #! database type, either mysql or postgres (required)
    type: ""
    #! database username (defaults to dataflow)
    username: "ZGF0YWZsb3cK"
    #! database password (default to secret)
    password: "c2VjcmV0Cg=="
  server:
    image:
      #! dataflow server image repository id
      repository: springcloud/spring-cloud-dataflow-server
      #! dataflow server image tag (required)
      tag: ""
    #! additional dataflow server configuration
    #@schema/type any=True
    config:
  ctr:
    image:
      #! ctr image repository id
      repository: springcloud/spring-cloud-dataflow-composed-task-runner
      #! ctr image tag (required)
      tag: ""
  skipper:
    image:
      #! skipper server image repository id
      repository: springcloud/spring-cloud-skipper-server
      #! skipper server image tag (required)
      tag: ""
  #! external binder settings, will disable binder deployment
  binder:
    kafka:
      host: ""
      port: 9092
    rabbit:
      host: ""
      port: 5672
  #! optional feature
  feature:
    monitoring:
      prometheus:
        enabled: false
        image:
          repository: springcloud/spring-cloud-dataflow-prometheus-local
          tag: ""
      grafana:
        enabled: false
        image:
          repository: springcloud/spring-cloud-dataflow-grafana-prometheus
          tag: ""
      prometheusRsocketProxy:
        enabled: false
        image:
          repository: micrometermetrics/prometheus-rsocket-proxy
          tag: 1.0.0
