#@data/values
---
scdf:
  deploy:
    binder: rabbit
  database:
    type: mysql
  server:
    image:
      tag: @project.version@
  ctr:
    image:
      tag: @project.version@
  skipper:
    image:
      tag: @spring-cloud-skipper.version@
  feature:
    monitoring:
      grafana:
        enabled: true
        image:
          tag: @project.version@
      prometheus:
        enabled: true
        image:
          tag: @project.version@
      prometheusRsocketProxy:
        enabled: true
