ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:main-docs: link:docs[]
endif::[]
ifndef::env-github[]
:main-docs: <<main-docs>>
endif::[]

= SCDF Carvel POC

This is a POC repo to create full https://carvel.dev[carvel dance] with scdf.

* Template k8s deployment files with `ytt`
* Create packages and package repos for `kapp-controller`.
* Have examples to:
** Manage deployment with package and package repos
** Manually deploy with `kapp`

[NOTE]
====
You need to have tools `kapp`, `kbld`, `ytt` and `imgpkg` installed from https://carvel.dev[carvel]
====

You can pick different routes to use this POC. Firstly have your _k8s_ environment running
on _minikube_ or a proper _cloud environment_, secondly choose how you want to deploy which would
be via `kapp-controller`, `kapp` or `kubectl`, and thirdly choose combination of _database_,
_binder_ and optional _features_ like monitoring.

[NOTE]
====
More detailed docs under {main-docs}.
====

== Examples
We go through few common examples how to deploy and manage dataflow.

=== Deploy via kapp-controller
`kapp-controller` is a most sophisticated way to handle lifecycle of a
_dataflow_ deployment on _k8s_ environment as existing _packages_ and
_package repos_ for a dataflow handles heavy lifting of where things
will get provisioned into an environment. It focuces on to just deploy
while allowing to customise deployed things with various options.

NOTE: If your starting from an empty _k8s_ environment never been prepared
for `kapp-controller` you need to do it before continuing.

Install `kapp-controller`:

Deploy controller:
[source, bash]
----
kapp deploy -y -a default-ns-rbac -f https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/develop/examples/rbac/default-ns.yml

kapp deploy -y -a kc -f https://raw.githubusercontent.com/jvalkeal/scdf-carvel-poc/main/examples/kapp-controller-ghcr.yml
----

After `kapp-controller` has been deployed you can deploy repositories for different stages
of a dataflow development and release channels like `snapshot`, `milestone` or `release`.

Deploy repository:

[source, bash]
----
kapp deploy -a scdf-repo-snapshot -f examples/scdf-repo-snapshot-ghcr.yml -y
kapp deploy -a scdf-repo-milestone -f examples/scdf-repo-milestone-ghcr.yml -y
kapp deploy -a scdf-repo-release -f examples/scdf-repo-release-ghcr.yml -y

kubectl get packagerepositories
NAME                          AGE     DESCRIPTION
scdf-milestone.tanzu.vmware   99s     Reconcile succeeded
scdf-release.tanzu.vmware     33s     Reconcile succeeded
scdf-snapshot.tanzu.vmware    2m35s   Reconcile succeeded

kubectl get packages
NAME                                   PACKAGEMETADATA NAME    VERSION          AGE
scdf.tanzu.vmware.com.2.8.0            scdf.tanzu.vmware.com   2.8.0            26s
scdf.tanzu.vmware.com.2.8.1            scdf.tanzu.vmware.com   2.8.1            27s
scdf.tanzu.vmware.com.2.8.2-SNAPSHOT   scdf.tanzu.vmware.com   2.8.2-SNAPSHOT   2m23s
scdf.tanzu.vmware.com.2.9.0-M1         scdf.tanzu.vmware.com   2.9.0-M1         1m30s
scdf.tanzu.vmware.com.2.9.0-SNAPSHOT   scdf.tanzu.vmware.com   2.9.0-SNAPSHOT   2m23s
----

NOTE: Above package and package repos are defined within public repos on a
VMWare space so you don't get trouble with rate limiting(which would be
a case with dockerhub).

Install `2.9.0-SNAPSHOT` with `postgres` and `rabbit`:

[source, bash]
----
kapp deploy -a scdf-demo -f examples/kapp-controller-scdf-290-snapshot-postgres-rabbit.yml -y

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION   AGE
scdf-demo   scdf.tanzu.vmware.com   2.9.0-SNAPSHOT    Reconciling   12s

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION           AGE
scdf-demo   scdf.tanzu.vmware.com   2.9.0-SNAPSHOT    Reconcile succeeded   88s
----

To try an upgrade, first install `2.8.0` with `postgres` and `rabbit`:
[source, bash]
----
kapp deploy -a scdf-demo -f examples/kapp-controller-scdf-280-postgres-rabbit.yml -y

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION           AGE
scdf-demo   scdf.tanzu.vmware.com   2.8.0             Reconcile succeeded   121m
----

Do an upgrade:
[source, bash]
----
kapp deploy -a scdf-demo -f examples/kapp-controller-scdf-281-postgres-rabbit.yml -y

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION           AGE
scdf-demo   scdf.tanzu.vmware.com   2.8.1             Reconcile succeeded   121m
----

Cleanup:

[source, bash]
----
kapp delete -a scdf-demo -y
kapp delete -a scdf-repo-snapshot -y
kapp delete -a scdf-repo-milestone -y
kapp delete -a scdf-repo-release -y
----

=== Deploy via kapp
Just using `kapp` and bypassing `kapp-controller` is a more straighforward way to deploy
things into _k8s_ without having a need to setup a controller environment. Essentially
it's just throwing out _k8s_ files into a cluster with some better control of what
`kapp` itself provides what comes for a deployment lifecycle. Essentially it is a step
above `kubectl` itself.

[source, bash]
----
kapp -y deploy -a scdf-demo -f <(ytt -f config -f examples/kapp-290-snapshot-monitoring.yml)
----

When you've done delete deployment

[source, bash]
----
kapp -y delete -a scdf-demo
----

=== Deploy via kubectl
Most low level of a deployment as you are essentially just _templating_ files via
`ytt` and throwing those into an environment. While deployment probably works as
is but you're then responsible to handle further actions like manually deleting
everything if that needs to be done or handle all other scenarious when things
are changed. Not really a recommended way unless you need to work with very
low level deployment files.

[source, bash]
----
ytt -f config -f examples/config-281-postgres.yml | kubectl apply -f-
----

== Project
Development notes about this POC.

=== Development
Deploying this POC into your minikube or cloud environment depends of view things
depending what you're actually doing. Packages and package repos needs a bit more
dance around pushing _bundles_ into _OCI_ repose so you're probably going to
have easier life just deploying things via `kapp` as `ytt` templates as once
that works it's easier to translate needed things into exiting bundles.

=== Testing
As templating gets more complex with with a lot of different user level options
to customize how actual k8s yaml files are laid out from templating, testing
is even more critical thing. Currently a choice was made to do testing via
npm/typescript as it gives relatively nice hooks to execute command line
programs like `ytt` and pass output to other npm libs like official model
classes to assert correct resulting k8s models.

As with normal dance with npm, you need to have `node` and `npm` installed and
tests can be run with:

[source, bash]
----
$ npm install

$ npm run test
----

=== Random Notes
Just notes needed for development and checking things out.

==== Checking Bundles

[source, bash]
----
imgpkg pull -b ghcr.io/jvalkeal/springcloud/scdf-repo:snapshot -o scdf-repo-snapshot
imgpkg pull -b ghcr.io/jvalkeal/springcloud/scdf-package:2.9.0-SNAPSHOT -o scdf-package-snapshot
----

Repo bundles are relocated into `jvalkeal/airgapped`:

[source, bash]
----
imgpkg pull -b ghcr.io/jvalkeal/airgapped/scdf-repo:snapshot -o airgapped-scdf-repo-snapshot
----

Looking _ImagesLock_ in airgapped repo it points to something like which then itself have
_ImagesLock_ for package images pointing to airgapped location:

[source, bash]
----
imgpkg pull -b ghcr.io/jvalkeal/airgapped/scdf-repo@sha256:51e99e890f9158cb9463b859e2c6a3918ebdc29809ee82573b3abe3aebc5b9f9 -o airgapped-scdf-package-snapshot
----

==== Airgap kapp-controller
`kapp-controller` install still points to dockerhub so we want to relocate to
not hit rate limiting.

Download current release:
[source, bash]
----
curl -OL https://github.com/vmware-tanzu/carvel-kapp-controller/releases/latest/download/release.yml
----

Open and find image pointing to dockerhub and relocate it, for example:
[source, bash]
----
imgpkg copy \
  -i index.docker.io/k14s/kapp-controller@sha256:ee05e345582e51a02249a24adf67c53f65a5fcc404bd41e74cd22704674f211f \
  --to-repo ghcr.io/jvalkeal/k14s/kapp-controller
----

Fix image in `release.yml` to point to new location and update:

[source, bash]
----
mv release.yml examples/kapp-controller-ghcr.yml
----

