ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
:main-docs: link:docs[]
endif::[]
ifndef::env-github[]
:main-docs: <<main-docs>>
endif::[]

= SCDF Carvel POC

This is a POC repo to create full https://carvel.dev[carvel dance] with scdf.

* Template k8s deployment files with `ytt`
* Create packages and package repos for `kapp-controller`.
* Have examples to:
** Manage deployment with package and package repos
** Manually deploy with `kapp`
** Manually deploy with `tanzu`

[NOTE]
====
You need to have tools `kapp`, `kbld`, `ytt` and `imgpkg` installed from https://carvel.dev[carvel]
====

You can pick different routes to use this POC. Firstly have your _k8s_ environment running
on _minikube_ or a proper _cloud environment_, secondly choose how you want to deploy which would
be via `kapp-controller`, `kapp` or `kubectl`, and thirdly choose combination of _database_,
_binder_ and optional _features_ like monitoring.

[NOTE]
====
More detailed docs under {main-docs}.
====


== Project
Development notes about this POC.

=== Development
Deploying this POC into your minikube or cloud environment depends of view things
depending what you're actually doing. Packages and package repos needs a bit more
dance around pushing _bundles_ into _OCI_ repose so you're probably going to
have easier life just deploying things via `kapp` as `ytt` templates as once
that works it's easier to translate needed things into exiting bundles.

=== Testing
As templating gets more complex with with a lot of different user level options
to customize how actual k8s yaml files are laid out from templating, testing
is even more critical thing. Currently a choice was made to do testing via
npm/typescript as it gives relatively nice hooks to execute command line
programs like `ytt` and pass output to other npm libs like official model
classes to assert correct resulting k8s models.

As with normal dance with npm, you need to have `node` and `npm` installed and
tests can be run with:

[source, bash]
----
$ npm install

$ npm run test
----

