#!/bin/bash

export DATAFLOW_VERSION=2.9.0-SNAPSHOT
export SKIPPER_VERSION=2.8.0-SNAPSHOT

rm -fr tanzu/generated && \
mkdir -p tanzu/generated/snapshot/packages && \
mkdir -p tanzu/generated/snapshot/.imgpkg && \
mkdir -p tanzu/generated/package && \

cp -R tanzu/templates/package/scdf/* tanzu/generated/package && \
find tanzu/generated/package -type f | xargs sed -i "s/@project.version@/$DATAFLOW_VERSION/g" && \
find tanzu/generated/package -type f | xargs sed -i "s/@spring-cloud-skipper.version@/$SKIPPER_VERSION/g" && \
(cd tanzu/generated/package/bundle && vendir sync) && \
kbld --file tanzu/generated/package/bundle --imgpkg-lock-output tanzu/generated/package/bundle/.imgpkg/images.yml && \
imgpkg push --bundle index.docker.io/jvalkeal/scdf:$DATAFLOW_VERSION --file tanzu/generated/package/bundle && \
ytt -f tanzu/templates/repo/scdf/package.yml -f tanzu/templates/repo/scdf/snapshot.yml > tanzu/generated/snapshot/packages/packages.yml && \
kbld --file tanzu/generated/snapshot/packages --imgpkg-lock-output tanzu/generated/snapshot/.imgpkg/images.yml && \
cp tanzu/templates/package/scdf/metadata.yml tanzu/generated/snapshot/packages && \
imgpkg push -b index.docker.io/jvalkeal/scdf-repo:snapshot -f tanzu/generated/snapshot && \
ytt -f tanzu/templates/repo/scdf/package-repository.yml -f tanzu/templates/repo/scdf/snapshot.yml > tanzu/generated/scdf-repo-snapshot.yml && \

echo

