apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: scdf.tanzu.vmware.com
  namespace: scdf
spec:
  displayName: "scdf"
  longDescription: "Spring Cloud Data Flow"
  shortDescription: "Spring Cloud Data Flow"
  providerName: VMware
  maintainers:
  - name: Janne Valkealahti
  categories:
    - "dataflow"
