#@ load("@ytt:data", "data")
#@ load("/common/common.star", "service_spec_type")

kind: Service
apiVersion: v1
metadata:
  name: scdf-server
  labels:
    app: scdf-server
    spring-deployment-id: scdf
spec:
  type: #@ service_spec_type()
  ports:
  - port: 80
    targetPort: 9393
    name: scdf-server
  selector:
    app: scdf-server
