#@ load("/db/db.lib.yml", "dataflow_datasource_config")

#@ def dataflow_platform_config():
limits:
  memory: 1024Mi
#@ end

#@ def dataflow_config():
---
spring:
  cloud:
    dataflow:
      task:
        platform:
          kubernetes:
            accounts:
              default: #@ dataflow_platform_config()
  datasource: #@ dataflow_datasource_config()
#@ end
