#@data/values
---
package_repository:
  schema:
    title: scdf.tanzu.vmware.com values schema
    properties:
      scdf:
        type: object
        description: SCDF configuration
        properties:
          deploy:
            type: object
            description: Deploy configuration
            properties:
              mode:
                type: string
                description: Deploy type
                enum:
                - minikube
                - cloud
                default: minikube
              binder:
                type: object
                description: Deploy Binder configuration
                properties:
                  enabled:
                    type: boolean
                    description: If binder deploy is enabled
                    default: true
                  type:
                    type: string
                    description: Binder type
                    enum:
                    - rabbit
                    - kafka
                    default: rabbit
                    examples:
                    - rabbit
                    - kafka
              database:
                type: object
                description: Deploy Database configuration
                properties:
                  enabled:
                    type: boolean
                    description: If database deploy is enabled
                    default: true
                  type:
                    type: string
                    description: Database type
                    enum:
                    - postgres
                    - mysql
                  username:
                    type: string
                    description: Database username
                  password:
                    type: string
                    description: Database password
