openapi: 3.0.3
info:
  version: 1.0.0
  title: Openapi schema for scdf
components:
  schemas:
    scdfPackage:
      type: object
      description: Schema for carvel package
      properties:
        scdf:
          type: object
          properties:
            deploy:
              type: object
              properties:
                mode:
                  type: string
                binder:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    type:
                      type: string
                      enum:
                        - rabbit
                        - kafka
                    rabbit:
                      type: object
                      properties:
                        config:
                          type: string
                        username:
                          type: string
                        password:
                          type: string
                database:
                  type: object
                  properties:
                    enabled:
                      type: boolean
    scdfYtt:
      type: object
      description: Extension to scdfPackage schema adding properties for plain ytt
      properties:
        scdf:
          type: object
          properties:
            binder:
              type: object
              properties:
                rabbit:
                  type: object
                  properties:
                    image:
                      type: object
                      properties:
                        repository:
                          type: string
                        tag:
                          type: string
                        digest:
                          type: string
paths: {}
