openapi: 3.0.3
info:
  version: 1.0.0
  title: Openapi schema for scdf
components:
  schemas:
    scdfPackage:
      type: object
      title: scdf values schema
      description: Schema for carvel package
      properties:
        scdf:
          type: object
          properties:
            deploy:
              type: object
              properties:
                mode:
                  type: string
                binder:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                      description: Enables binder deployment
                    type:
                      type: string
                      default: rabbit
                      enum:
                        - rabbit
                        - kafka
                      description: Defines a binder type if deployment is enabled, either rabbit or kafka
                    rabbit:
                      type: object
                      properties:
                        config:
                          type: string
                        username:
                          type: string
                        password:
                          type: string
                database:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                      default: true
                      description: Enables database deployment
                    type:
                      type: string
                      default: postgres
                      enum:
                        - mysql
                        - postgres
                      description: Defines a database type if deployment is enabled, either mysql or postgres
                    postgres:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                    mysql:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
            server:
              type: object
              properties:
                database:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    driverClassName:
                      type: string
                    validationQuery:
                      type: string
                    testOnBorrow:
                      type: boolean
                config:
                  type: string
                metrics:
                  type: object
                  properties:
                    dashboard:
                      type: object
                      properties:
                        url:
                          type: string
            skipper:
              type: object
              properties:
                database:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    driverClassName:
                      type: string
                    validationQuery:
                      type: string
                    testOnBorrow:
                      type: boolean
                config:
                  type: string
            binder:
              type: object
              properties:
                kafka:
                  type: object
                  properties:
                    host:
                      type: string
                      description: External kafka host
                    port:
                      type: string
                      description: External kafka port
                rabbit:
                  type: object
                  properties:
                    host:
                      type: string
                      description: External rabbit host
                    port:
                      type: string
                      description: External rabbit port
                    username:
                      type: string
                      description: External rabbit username
                    password:
                      type: string
                      description: External rabbit password
            feature:
              type: object
              properties:
                monitoring:
                  type: object
                  properties:
                    prometheus:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: false
                          description: Enables prometheus feature
                    prometheusRsocketProxy:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: false
                          description: Enables prometheus rsocket proxy feature
                    grafana:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                          default: false
                          description: Enables grafana feature
    scdfYtt:
      type: object
      description: Extension to scdfPackage schema adding properties for plain ytt
      properties:
        scdf:
          type: object
          properties:
            binder:
              type: object
              properties:
                rabbit:
                  type: object
                  properties:
                    image:
                      type: object
                      properties:
                        repository:
                          type: string
                        tag:
                          type: string
                        digest:
                          type: string
paths: {}
