openapi: 3.0.3
info:
  version: 1.0.0
  title: Openapi schema for scdf
components:
  schemas:
    scdfPackage:
      type: object
      title: scdf values schema
      description: Schema for carvel package
      properties:
        scdf:
          type: object
          properties:
            deploy:
              type: object
              properties:
                mode:
                  type: string
                binder:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    type:
                      type: string
                      enum:
                        - rabbit
                        - kafka
                    rabbit:
                      type: object
                      properties:
                        config:
                          type: string
                        username:
                          type: string
                        password:
                          type: string
                database:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    type:
                      type: string
                      enum:
                        - mysql
                        - postgres
                    postgres:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
                    mysql:
                      type: object
                      properties:
                        username:
                          type: string
                        password:
                          type: string
            server:
              type: object
              properties:
                database:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    driverClassName:
                      type: string
                    validationQuery:
                      type: string
                    testOnBorrow:
                      type: boolean
                config:
                  type: string
                metrics:
                  type: object
                  properties:
                    dashboard:
                      type: object
                      properties:
                        url:
                          type: string
            skipper:
              type: object
              properties:
                database:
                  type: object
                  properties:
                    username:
                      type: string
                    password:
                      type: string
                    driverClassName:
                      type: string
                    validationQuery:
                      type: string
                    testOnBorrow:
                      type: boolean
                config:
                  type: string
            binder:
              type: object
              properties:
                kafka:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: string
                rabbit:
                  type: object
                  properties:
                    host:
                      type: string
                    port:
                      type: string
                    username:
                      type: string
                    password:
                      type: string
            feature:
              type: object
              properties:
                monitoring:
                  type: object
                  properties:
                    prometheus:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                    prometheusRsocketProxy:
                      type: object
                      properties:
                        enabled:
                          type: boolean
                    grafana:
                      type: object
                      properties:
                        enabled:
                          type: boolean
    scdfYtt:
      type: object
      description: Extension to scdfPackage schema adding properties for plain ytt
      properties:
        scdf:
          type: object
          properties:
            binder:
              type: object
              properties:
                rabbit:
                  type: object
                  properties:
                    image:
                      type: object
                      properties:
                        repository:
                          type: string
                        tag:
                          type: string
                        digest:
                          type: string
paths: {}
