#@ load("postgres.lib.yml", "name")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: postgres:10
        name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-root-password
              name: #@ name()
        - name: POSTGRES_USER
          value: spring
        - name: POSTGRES_DB
          value: #@ name()
        ports:
        - containerPort: 5432
          name: #@ name()
        #!volumeMounts:
        #!- name: data
        #!  mountPath: /var/lib/mysql
        #!args:
        #!- "--ignore-db-dir=lost+found"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: #@ name()
