#@ load("prometheus-rsocket-proxy.lib.yml", "name", "prometheus_rsocket_proxy_image")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: #@ prometheus_rsocket_proxy_image()
        name: prometheus-rsocket-proxy
        ports:
        - containerPort: 9096
          name: #@ name()
