#@ load("@ytt:data", "data")

#@ def name(): return data.values.name

#@ def skipper_datasource():
url: jdbc:postgresql://${DB-SKIPPER_SERVICE_HOST}:${DB-SKIPPER_SERVICE_PORT}/db-skipper
username: spring
password: ${postgres-root-password}
driverClassName: org.postgresql.Driver
#@ end
---
#@ def dataflow_datasource():
url: jdbc:postgresql://${DB-DATAFLOW_SERVICE_HOST}:${DB-DATAFLOW_SERVICE_PORT}/db-dataflow
username: spring
password: ${postgres-root-password}
driverClassName: org.postgresql.Driver
#@ end
---
