#@ load("@ytt:library", "library")
#@ load("db.star", "mysql_enabled", "postgres_enabled")

#@ def skipper_datasource_config():
#@   if mysql_enabled():
#@      fun = library.get("mysql").with_data_values({}).export("skipper_datasource")
#@      return fun()
#@   elif postgres_enabled():
#@      fun = library.get("postgres").with_data_values({}).export("skipper_datasource")
#@      return fun()
#@   end
#@ end

#@ def dataflow_datasource_config():
#@   if mysql_enabled():
#@      fun = library.get("mysql").with_data_values({}).export("dataflow_datasource")
#@      return fun()
#@   elif postgres_enabled():
#@      fun = library.get("postgres").with_data_values({}).export("dataflow_datasource")
#@      return fun()
#@   end
#@ end

---
#@ def db_overlay():
#@ end
