#@ load("kafka.lib.yml", "name")
#@ load("kafka.lib.yml", "zk_name")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ zk_name()
  labels:
    app: #@ name()
    component: #@ zk_name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ zk_name()
  template:
    metadata:
      labels:
        app: #@ zk_name()
        component: #@ zk_name()
    spec:
      containers:
      - name: #@ zk_name()
        image: confluentinc/cp-zookeeper:5.5.2
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
