#@ load("kafka.lib.yml", "name")
#@ load("kafka.lib.yml", "broker_name")
apiVersion: v1
kind: Service
metadata:
  name: #@ broker_name()
  labels:
    app: #@ name()
    component: #@ broker_name()
spec:
  clusterIP: None
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: #@ name()
    component: #@ broker_name()
