#@ load("@ytt:data", "data")
#@ load("kafka.star", "name")
#@ load("kafka.star", "broker_name")
#@ load("kafka.star", "zk_name")
#@ load("kafka.star", "zk_client_name")
#@ load("kafka.star", "zk_server_name")

#@ def broker_image():
#@   return data.values.brokerImage.repository + ":" + data.values.brokerImage.tag
#@ end

#@ def zk_image():
#@   return data.values.zkImage.repository + ":" + data.values.zkImage.tag
#@ end
