#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("db/db.lib.yml", "dataflow_datasource_config")

#@ def dataflow_platform_config():
limits:
  memory: 1024Mi
#@ end

#@ def base_config():
config:
  spring:
    cloud:
      dataflow:
        task:
          platform:
            kubernetes:
              accounts:
                default: #@ dataflow_platform_config()
    datasource: #@ dataflow_datasource_config()
#@ end

#@ def user_config():
#@ if data.values.scdf.server.config:
#@overlay/match-child-defaults missing_ok=True
config: #@ data.values.scdf.server.config
#@ end
#@ end

#@ def dataflow_config():
--- #@ template.replace([overlay.apply(base_config(), user_config())["config"]])
#@ end
