#@ load("@ytt:template", "template")
#@ load("@ytt:overlay", "overlay")
#@ load("monitoring/monitoring.lib.yml", "monitoring_config")
#@ load("monitoring/monitoring.star", "grafana_enabled")
#@ load("common/common.star", "service_spec_type")

#@ if grafana_enabled():
--- #@ template.replace(overlay.apply(monitoring_config(service_spec_type())))
#@ end
