#@ load("@ytt:data", "data")
#@ load("skipper.star", "skipper_image", "skipper_container_env")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skipper
  labels:
    app: skipper
spec:
  selector:
    matchLabels:
      app: skipper
  replicas: 1
  template:
    metadata:
      labels:
        app: skipper
    spec:
      containers:
      - name: skipper
        image: #@ skipper_image()
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /workspace/config
          readOnly: true
        - name: database
          mountPath: /etc/secrets/database
          readOnly: true
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 7577
          initialDelaySeconds: 45
        readinessProbe:
          httpGet:
            path: /actuator/info
            port: 7577
          initialDelaySeconds: 45
        resources:
          limits:
            cpu: 1.0
            memory: 1024Mi
          requests:
            cpu: 0.5
            memory: 640Mi
        env: #@ skipper_container_env()
      serviceAccountName: scdf-sa
      volumes:
      - name: config
        configMap:
          name: skipper
          items:
          - key: application.yaml
            path: application.yaml
      - name: database
        secret:
          secretName: db-skipper
