#@ load("grafana.lib.yml", "name", "service_spec_type")

apiVersion: v1
kind: Service
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  selector:
    app: #@ name()
  type: #@ service_spec_type()
  ports:
    - port: 3000
      targetPort: 3000
