#@ load("grafana.lib.yml", "name")

apiVersion: v1
kind: Service
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  selector:
    app: #@ name()
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
