#@ load("@ytt:data", "data")
#@ load("/common/common.star", "service_spec_type")

apiVersion: v1
kind: Service
metadata:
  name: skipper
  labels:
    app: skipper
    spring-deployment-id: scdf
spec:
  type: #@ service_spec_type()
  ports:
  - port: 80
    targetPort: 7577
  selector:
    app: skipper
