#@ load("skipper.star", "env_config")
#@ load("/db/db.lib.yml", "skipper_datasource_config")

#@ def skipper_platform_config():
environmentVariables: #@ env_config()
limits:
  memory: 1024Mi
  cpu: 500m
readinessProbeDelay: 120
livenessProbeDelay: 90
#@ end

#@ def skipper_config():
---
spring:
  cloud:
    skipper:
      server:
        platform:
          kubernetes:
            accounts:
              default: #@ skipper_platform_config()
  datasource: #@ skipper_datasource_config()
#@ end
