#@ load("@ytt:data", "data")
#@ load("/common/common.lib.yml", "rabbitmq_enabled")
#@ if rabbitmq_enabled():
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  ports:
  - port: 5672
  selector:
    app: rabbitmq
#@ end
