#@ load("@ytt:data", "data")
---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: scdf-demo
spec:
  serviceAccountName: default-ns-sa
  packageRef:
    refName: scdf.tanzu.vmware.com
    versionSelection:
      constraints: #@ data.values.package
      prereleases: {}
  values:
  - secretRef:
      name: scdf-demo-values
---
apiVersion: v1
kind: Secret
metadata:
  name: scdf-demo-values
stringData:
  #@yaml/text-templated-strings
  values.yml: |
    ---
    scdf:
      deploy:
        mode: cloud
        binder: 
          type: (@= data.values.broker @)
        database:
          type: (@= data.values.database @)
