title: scdf.tanzu.vmware.com values schema
properties:
  scdf:
    type: object
    description: SCDF configuration
    properties:
      deploy:
        type: object
        description: Deploy configuration
        properties:
          mode:
            type: string
            description: Deploy type
            enum:
            - minikube
            - cloud
            default: minikube
          binder:
            type: string
            description: Binder type
            enum:
            - rabbit
            - kafka
            default: rabbit
            examples:
            - rabbit
            - kafka
      database:
        type: object
        description: Database configuration
        properties:
          type:
            type: string
            description: Database type
            enum:
            - postgres
            - mysql
          username:
            type: string
            description: Database username
          password:
            type: string
            description: Database password
      server:
        type: object
        properties:
          image:
            type: object
            properties:
              repository:
                type: string
              tag:
                type: string
          config:
            type: string
