#! Conditionally create configs for dataflow db by choosing different db types

#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("db.lib.yml", "db_overlay")
#@ load("db.star", "mysql_enabled")
#@ load("db.star", "postgres_enabled")
#@ load("db.star", "db_username")
#@ load("db.star", "db_password")

#@ def db_values():
name: db-dataflow
username: #@ db_username()
password: #@ db_password()
#@ end

#@ if mysql_enabled():
--- #@ template.replace(overlay.apply(library.get("mysql").with_data_values(db_values()).eval(), db_overlay()))
#@ end

#@ if postgres_enabled():
--- #@ template.replace(overlay.apply(library.get("postgres").with_data_values(db_values()).eval(), db_overlay()))
#@ end
