#! Conditionally create configs for dataflow db by choosing different db types

#@ load("@ytt:library", "library")
#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:template", "template")
#@ load("db.lib.yml", "db_overlay")
#@ load("/db/db.star", "mysql_enabled", "postgres_enabled")

#@ if mysql_enabled():
--- #@ template.replace(overlay.apply(library.get("mysql").with_data_values({"name": "db-skipper"}).eval(), db_overlay()))
#@ end

#@ if postgres_enabled():
--- #@ template.replace(overlay.apply(library.get("postgres").with_data_values({"name": "db-skipper"}).eval(), db_overlay()))
#@ end
