== Examples
We go through few common examples how to deploy and manage dataflow.

=== Deploy via kapp-controller
`kapp-controller` is a most sophisticated way to handle lifecycle of a
_dataflow_ deployment on _k8s_ environment as existing _packages_ and
_package repos_ for a dataflow handles heavy lifting of where things
will get provisioned into an environment. It focuces on to just deploy
while allowing to customise deployed things with various options.

NOTE: If your starting from an empty _k8s_ environment never been prepared
for `kapp-controller` you need to do it before continuing.

Install `kapp-controller`:

Deploy controller:
[source, bash]
----
kapp deploy -y -a default-ns-rbac -f https://raw.githubusercontent.com/vmware-tanzu/carvel-kapp-controller/develop/examples/rbac/default-ns.yml

kapp deploy -y -a kc -f https://raw.githubusercontent.com/jvalkeal/scdf-carvel-poc/main/examples/kapp-controller-ghcr.yml
----

After `kapp-controller` has been deployed you can deploy repositories for different stages
of a dataflow development and release channels like `snapshot`, `milestone` or `release`.

Deploy repository:

[source, bash]
----
kapp deploy -a scdf-repo-snapshot -f examples/scdf-repo-snapshot-ghcr.yml -y
kapp deploy -a scdf-repo-milestone -f examples/scdf-repo-milestone-ghcr.yml -y
kapp deploy -a scdf-repo-release -f examples/scdf-repo-release-ghcr.yml -y

kubectl get packagerepositories
NAME                          AGE     DESCRIPTION
scdf-milestone.tanzu.vmware   99s     Reconcile succeeded
scdf-release.tanzu.vmware     33s     Reconcile succeeded
scdf-snapshot.tanzu.vmware    2m35s   Reconcile succeeded

kubectl get packages
NAME                                   PACKAGEMETADATA NAME    VERSION          AGE
scdf.tanzu.vmware.com.2.8.0            scdf.tanzu.vmware.com   2.8.0            26s
scdf.tanzu.vmware.com.2.8.1            scdf.tanzu.vmware.com   2.8.1            27s
scdf.tanzu.vmware.com.2.8.2-SNAPSHOT   scdf.tanzu.vmware.com   2.8.2-SNAPSHOT   2m23s
scdf.tanzu.vmware.com.2.9.0-M1         scdf.tanzu.vmware.com   2.9.0-M1         1m30s
scdf.tanzu.vmware.com.2.9.0-SNAPSHOT   scdf.tanzu.vmware.com   2.9.0-SNAPSHOT   2m23s
----

NOTE: Above package and package repos are defined within public repos on a
VMWare space so you don't get trouble with rate limiting(which would be
a case with dockerhub).

Install `2.9.0-SNAPSHOT` with `postgres` and `rabbit`:

[source, bash]
----
kapp deploy -a scdf-demo -f examples/kapp-controller/290-snapshot-postgres-rabbit.yml -y

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION   AGE
scdf-demo   scdf.tanzu.vmware.com   2.9.0-SNAPSHOT    Reconciling   12s

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION           AGE
scdf-demo   scdf.tanzu.vmware.com   2.9.0-SNAPSHOT    Reconcile succeeded   88s
----

To try an upgrade, first install `2.8.0` with `postgres` and `rabbit`:
[source, bash]
----
kapp deploy -a scdf-demo -f examples/kapp-controller/280-postgres-rabbit.yml -y

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION           AGE
scdf-demo   scdf.tanzu.vmware.com   2.8.0             Reconcile succeeded   121m
----

Do an upgrade:
[source, bash]
----
kapp deploy -a scdf-demo -f examples/kapp-controller/281-postgres-rabbit.yml -y

kubectl get packageinstalls
NAME        PACKAGE NAME            PACKAGE VERSION   DESCRIPTION           AGE
scdf-demo   scdf.tanzu.vmware.com   2.8.1             Reconcile succeeded   121m
----

Cleanup:

[source, bash]
----
kapp delete -a scdf-demo -y
kapp delete -a scdf-repo-snapshot -y
kapp delete -a scdf-repo-milestone -y
kapp delete -a scdf-repo-release -y
----

=== Deploy via kapp
Just using `kapp` and bypassing `kapp-controller` is a more straighforward way to deploy
things into _k8s_ without having a need to setup a controller environment. Essentially
it's just throwing out _k8s_ files into a cluster with some better control of what
`kapp` itself provides what comes for a deployment lifecycle. Essentially it is a step
above `kubectl` itself.

[source, bash]
----
kapp -y deploy -a scdf-demo -f <(ytt -f config -f examples/kapp/290-snapshot-monitoring.yml)
----

When you've done delete deployment

[source, bash]
----
kapp -y delete -a scdf-demo
----

=== Deploy via kubectl
Most low level of a deployment as you are essentially just _templating_ files via
`ytt` and throwing those into an environment. While deployment probably works as
is but you're then responsible to handle further actions like manually deleting
everything if that needs to be done or handle all other scenarious when things
are changed. Not really a recommended way unless you need to work with very
low level deployment files.

[source, bash]
----
ytt -f config -f examples/ytt/281-postgres.yml | kubectl apply -f-
----
