#@ load("mysql.lib.yml", "name")

apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: mysql:5.7.25
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mysql-root-password
              name: #@ name()
        - name: MYSQL_DATABASE
          value: #@ name()
        ports:
        - containerPort: 3306
          name: #@ name()
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        args:
        - "--ignore-db-dir=lost+found"
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: #@ name()
