#@ load("mysql.lib.yml", "name", "username", "password")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  mysql-root-username: #@ username()
  mysql-root-password: #@ password()
