name: Release Repo Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jvalkeal
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Envs
      run: |
        echo RTAG=$(date +%y%m%d%s%N) >> $GITHUB_ENV
        echo TAG=release >> $GITHUB_ENV
    - name: Tanzu Dance
      run: |
        rm -fr templates/generated
        mkdir -p templates/generated/release/packages
        mkdir -p templates/generated/release/.imgpkg
        ytt -f templates/repo/scdf/package.yml -f templates/repo/scdf/release.yml -f templates/repo/scdf/openapi.yml > templates/generated/release/packages/packages.yml
        kbld --file templates/generated/release/packages --imgpkg-lock-output templates/generated/release/.imgpkg/images.yml
        ytt -f templates/repo/scdf/metadata.yml --data-value name=scdf-repo-release.tanzu.vmware.com --output-files templates/generated/release/packages
        imgpkg push --bundle ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG -f templates/generated/release
        docker pull ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG-$RTAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG-$RTAG
