name: Release Repo Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jvalkeal
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Tanzu Dance
      run: |
        rm -fr tanzu/generated
        mkdir -p tanzu/generated/release/packages
        mkdir -p tanzu/generated/release/.imgpkg
        ytt -f tanzu/templates/repo/scdf/package.yml -f tanzu/templates/repo/scdf/release.yml > tanzu/generated/release/packages/packages.yml
        kbld --file tanzu/generated/release/packages --imgpkg-lock-output tanzu/generated/release/.imgpkg/images.yml
        ytt -f tanzu/templates/repo/scdf/metadata.yml --data-value name=scdf-repo-release.tanzu.vmware.com --output-files tanzu/generated/release/packages
        imgpkg push -b ghcr.io/jvalkeal/scdf-repo:release -f tanzu/generated/release
