name: Snapshot Package Publish 29x

on:
  workflow_dispatch:
  push:

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jvalkeal
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Envs
      run: |
        echo DATAFLOW_VERSION=2.9.0-SNAPSHOT >> $GITHUB_ENV
        echo SKIPPER_VERSION=2.8.0-SNAPSHOT >> $GITHUB_ENV
        echo RTAG=$(date +%y%m%d%s%N) >> $GITHUB_ENV
        echo TAG=2.9.0-SNAPSHOT >> $GITHUB_ENV
    - name: Tanzu Dance
      run: |
        ytt \
          -f tanzu/templates/package/scdf \
          --output-files tanzu/generated/package/scdf \
          --data-value-yaml project.version=$DATAFLOW_VERSION \
          --data-value-yaml spring.cloud.skipper.version=$SKIPPER_VERSION \
          --file-mark 'bundle/config/values.yml:type=text-template'
        ytt \
          -f tanzu/templates/values \
          --output-files tanzu/generated/values \
          --data-value-yaml project.version=$DATAFLOW_VERSION \
          --data-value-yaml spring.cloud.skipper.version=$SKIPPER_VERSION \
          --file-mark 'config1.yml:type=text-template' \
          --file-mark 'config2.yml:type=text-template'
        vendir sync --chdir tanzu/generated/package/scdf/bundle
        kbld \
          -f <(ytt -f tanzu/generated/package/scdf/bundle -f tanzu/generated/values/config1.yml) \
          -f <(ytt -f tanzu/generated/package/scdf/bundle -f tanzu/generated/values/config2.yml) \
          --imgpkg-lock-output tanzu/generated/package/scdf/bundle/.imgpkg/images.yml
        imgpkg push --bundle ghcr.io/jvalkeal/springcloud/scdf-package:$RTAG --file tanzu/generated/package/scdf/bundle
        docker pull ghcr.io/jvalkeal/springcloud/scdf-package:$RTAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-package:$RTAG ghcr.io/jvalkeal/springcloud/scdf-package:$TAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-package:$RTAG ghcr.io/jvalkeal/springcloud/scdf-package:$TAG-$RTAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-package:$TAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-package:$TAG-$RTAG
