name: Snapshot Repo Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Tanzu Dance
      run: |
        rm -fr tanzu/generated
        mkdir -p tanzu/generated/snapshot/packages
        mkdir -p tanzu/generated/snapshot/.imgpkg
        ytt -f tanzu/templates/repo/scdf/package.yml -f tanzu/templates/repo/scdf/snapshot.yml > tanzu/generated/snapshot/packages/packages.yml
        kbld --file tanzu/generated/snapshot/packages --imgpkg-lock-output tanzu/generated/snapshot/.imgpkg/images.yml
        ytt -f tanzu/templates/repo/scdf/metadata.yml --data-value name=scdf-repo-snapshot.tanzu.vmware.com --output-files tanzu/generated/snapshot/packages
        imgpkg push -b index.docker.io/jvalkeal/scdf-repo:snapshot -f tanzu/generated/snapshot
