# Build and publish snapshot of a configured repos
name: Snapshot Publish
on:
  push:
    branches:
      - main
jobs:
  snapshot:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - name: npm install
      run: npm install
