name: Snapshot Repo Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Snapshot Package Publish 29x"]
    types: [completed]

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jvalkeal
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Envs
      run: |
        echo RTAG=$(date +%y%m%d%s%N) >> $GITHUB_ENV
        echo TAG=snapshot >> $GITHUB_ENV
    - name: Tanzu Dance
      run: |
        rm -fr tanzu/generated
        mkdir -p tanzu/generated/snapshot/packages
        mkdir -p tanzu/generated/snapshot/.imgpkg
        ytt -f tanzu/templates/repo/scdf/package.yml -f tanzu/templates/repo/scdf/snapshot.yml -f tanzu/templates/repo/scdf/openapi.yml > tanzu/generated/snapshot/packages/packages.yml
        kbld --file tanzu/generated/snapshot/packages --imgpkg-lock-output tanzu/generated/snapshot/.imgpkg/images.yml
        ytt -f tanzu/templates/repo/scdf/metadata.yml --data-value name=scdf-repo-snapshot.tanzu.vmware.com --output-files tanzu/generated/snapshot/packages
        imgpkg push --bundle ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG -f tanzu/generated/snapshot
        docker pull ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG-$RTAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG-$RTAG
