name: Snapshot Repo Publish

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Snapshot Package Publish"]
    types: [completed]

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: jvalkeal
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Envs
      run: |
        echo RTAG=$(date +%y%m%d%s%N) >> $GITHUB_ENV
        echo TAG=snapshot >> $GITHUB_ENV
    - name: Tanzu Dance
      run: |
        rm -fr templates/generated
        mkdir -p templates/generated/snapshot/packages
        mkdir -p templates/generated/snapshot/.imgpkg
        ytt \
          -f templates/repo/scdf/package.yml \
          -f templates/repo/scdf/snapshot.yml \
          -f templates/repo/scdf/openapi.yml > templates/generated/snapshot/packages/packages.yml
        kbld \
          --file templates/generated/snapshot/packages \
          --imgpkg-lock-output templates/generated/snapshot/.imgpkg/images.yml
        ytt \
          -f templates/repo/scdf/metadata.yml \
          --data-value name=scdf-repo-snapshot.tanzu.vmware.com \
          --output-files templates/generated/snapshot/packages
        imgpkg push \
          --bundle ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG \
          -f templates/generated/snapshot
        docker pull ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG
        docker tag ghcr.io/jvalkeal/springcloud/scdf-repo:$RTAG ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG-$RTAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG
        docker push ghcr.io/jvalkeal/springcloud/scdf-repo:$TAG-$RTAG
