name: Snapshot Publish

on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish Snapshot
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 12
    - uses: vmware-tanzu/carvel-setup-action@v1
    - uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: setup env
      env:
        DATAFLOW_VERSION: 2.9.0-SNAPSHOT
        SKIPPER_VERSION: 2.8.0-SNAPSHOT
      run: |
        rm -fr tanzu/generated
        mkdir -p tanzu/generated/snapshot/packages
        mkdir -p tanzu/generated/snapshot/.imgpkg
        mkdir -p tanzu/generated/package
        cp -R tanzu/templates/package/scdf/* tanzu/generated/package
        find tanzu/generated/package -type f -exec sed -i "s/@project.version@/$DATAFLOW_VERSION/g" {} \;
        find tanzu/generated/package -type f -exec sed -i "s/@spring-cloud-skipper.version@/$SKIPPER_VERSION/g" {} \;
        (cd tanzu/generated/package/bundle
        kbld --file tanzu/generated/package/bundle --imgpkg-lock-output tanzu/generated/package/bundle/.imgpkg/images.yml
        imgpkg push --bundle index.docker.io/jvalkeal/scdf:$DATAFLOW_VERSION --file tanzu/generated/package/bundle
        ytt -f tanzu/templates/repo/scdf/package.yml -f tanzu/templates/repo/scdf/snapshot.yml > tanzu/generated/snapshot/packages/packages.yml
        kbld --file tanzu/generated/snapshot/packages --imgpkg-lock-output tanzu/generated/snapshot/.imgpkg/images.yml
        cp tanzu/templates/package/scdf/metadata.yml tanzu/generated/snapshot/packages
        imgpkg push -b index.docker.io/jvalkeal/scdf-repo:snapshot -f tanzu/generated/snapshot
