#@ load("postgres.lib.yml", "name", "username", "password")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  postgres-user: #@ username()
  postgres-password: #@ password()
