#@ load("postgres.lib.yml", "name")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  postgres-root-password: eW91cnBhc3N3b3Jk
  postgres-root-username: cm9vdA==
