#@ load("postgres.lib.yml", "name", "username", "password")

apiVersion: v1
kind: Secret
metadata:
  name: #@ name()
  labels:
    app: #@ name()
data:
  postgres-root-username: #@ username()
  postgres-root-password: #@ password()
