#@ load("rabbitmq.lib.yml", "name")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: rabbitmq:3.6.10
        name: #@ name()
        ports:
        - containerPort: 5672
