#@ load("rabbitmq.lib.yml", "name", "config_name")
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #@ name()
  labels:
    app: #@ name()
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #@ name()
  template:
    metadata:
      labels:
        app: #@ name()
    spec:
      containers:
      - image: rabbitmq:3.9.5
        name: #@ name()
        volumeMounts:
        - name: rabbitmq-config-volume
          mountPath: /etc/rabbitmq
        ports:
        - containerPort: 5672
      volumes:
      - name: rabbitmq-config-volume
        configMap:
          name: #@ config_name()
          items:
          - key: rabbitmq.conf
            path: rabbitmq.conf
